# Generated by Django 5.0.14 on 2026-03-18 15:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisorSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('interviewing', 'Interviewing'), ('complete', 'Complete')], default='interviewing', max_length=20)),
                ('question_count', models.IntegerField(default=0, help_text='Number of questions answered so far (0–10)')),
                ('profile_text', models.TextField(blank=True, help_text='Synthesised natural-language student profile after interview')),
                ('message_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'advisor_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdvisorMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='advisor.advisorsession')),
            ],
            options={
                'db_table': 'advisor_messages',
                'ordering': ['created_at'],
            },
        ),
    ]
