# Generated by Django 5.0.14 on 2026-05-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisor', '0002_alter_advisorsession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorsession',
            name='cached_recommendations',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
