# Generated by Django 5.0.14 on 2025-10-02 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Healthcare', 'Healthcare'), ('Engineering', 'Engineering'), ('Legal', 'Legal'), ('Finance', 'Finance'), ('Education', 'Education'), ('Creative', 'Creative Arts')], max_length=100)),
                ('icon', models.CharField(default='💼', max_length=10)),
                ('description', models.TextField()),
                ('avg_salary_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('job_demand_score', models.IntegerField(help_text='Score 1-100')),
                ('growth_rate', models.DecimalField(decimal_places=2, help_text='Percentage', max_digits=5)),
                ('work_life_balance_score', models.IntegerField(help_text='Score 1-100')),
                ('entry_requirements_score', models.IntegerField(help_text='Score 1-100')),
                ('job_satisfaction_score', models.IntegerField(help_text='Score 1-100')),
                ('education_required', models.TextField()),
                ('experience_required', models.TextField()),
                ('key_skills', models.JSONField(default=list)),
                ('top_employers', models.JSONField(default=list)),
                ('work_environment', models.CharField(max_length=200)),
                ('certifications', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'careers',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='careers_categor_06b8e1_idx'), models.Index(fields=['avg_salary_ksh'], name='careers_avg_sal_35fcba_idx')],
            },
        ),
        migrations.CreateModel(
            name='CareerProsCons',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('pros', 'Pros'), ('cons', 'Cons')], max_length=10)),
                ('items', models.JSONField(default=list)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pros_cons', to='careers.career')),
            ],
            options={
                'db_table': 'career_pros_cons',
                'unique_together': {('career', 'type')},
            },
        ),
    ]
