# Generated by Django 5.0.14 on 2025-10-07 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='votable_type',
            field=models.CharField(choices=[('post', 'Post'), ('comment', 'Comment'), ('society_post', 'Society Post')], max_length=20),
        ),
    ]
