# Generated by Django 5.0.14 on 2025-10-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0003_careerhub_banner_image_careerhub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerhub',
            name='icon_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
