# Generated by Django 5.0.14 on 2025-10-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0006_alter_comment_updated_at_alter_post_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerhub',
            name='related_societies',
            field=models.JSONField(blank=True, default=list, help_text='List of related professional societies'),
        ),
    ]
