# Generated by Django 5.0.14 on 2026-05-18 08:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0007_careerhub_related_societies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.TextField(blank=True, help_text='Image URL or base64 data for image-type posts', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True, help_text='External URL for link-type posts', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('question', 'Question'), ('guide', 'Guide'), ('discussion', 'Discussion'), ('success_story', 'Success Story'), ('link', 'Link'), ('image', 'Image')], max_length=20),
        ),
        migrations.CreateModel(
            name='AffiliatedInstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('institution_type', models.CharField(choices=[('school', 'School / University'), ('bootcamp', 'Bootcamp'), ('company', 'Company'), ('ngo', 'NGO / Non-profit')], max_length=20)),
                ('logo_emoji', models.CharField(blank=True, default='🏛️', max_length=10)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('website', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified by EduPath admins')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_institutions', to=settings.AUTH_USER_MODEL)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliated_institutions', to='hubs.careerhub')),
            ],
            options={
                'db_table': 'hub_affiliated_institutions',
                'ordering': ['-is_verified', 'name'],
                'indexes': [models.Index(fields=['hub', 'is_verified'], name='hub_affilia_hub_id_a0e49d_idx')],
            },
        ),
        migrations.CreateModel(
            name='HubMembership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('associate', 'Associate'), ('mentor', 'Mentor'), ('moderator', 'Moderator'), ('institution', 'Institution')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('role_granted_at', models.DateTimeField(blank=True, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='hubs.careerhub')),
                ('role_granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_hub_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hub_memberships',
                'indexes': [models.Index(fields=['hub', 'role'], name='hub_members_hub_id_25bd06_idx')],
                'unique_together': {('hub', 'user')},
            },
        ),
    ]
