# Generated by Django 5.0.14 on 2026-05-18 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0007_careerhub_related_societies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Associate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('associate_type', models.CharField(choices=[('MENTOR', 'Mentor'), ('SOCIETY', 'Society'), ('SCHOOL', 'School')], max_length=20)),
                ('bio', models.TextField()),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_suspended', models.BooleanField(default=False)),
                ('strike_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associates', to='hubs.careerhub')),
            ],
            options={
                'db_table': 'associates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssociatePost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('OPPORTUNITY', 'Opportunity'), ('EVENT', 'Event')], max_length=20)),
                ('content', models.TextField()),
                ('image_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('upvotes', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='associates.associate')),
            ],
            options={
                'db_table': 'associate_posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('ACTIONED', 'Actioned'), ('DISMISSED', 'Dismissed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associate_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='associates.associatepost')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'moderation_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
