# Generated by Django 5.0.14 on 2026-05-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='admin_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associate',
            name='application_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_RESPONSE', 'Awaiting Response'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='associate',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
