# Generated by Django 5.0.14 on 2026-05-19 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0002_associate_admin_notes_associate_application_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='associatepost',
            old_name='content',
            new_name='body',
        ),
        migrations.AddField(
            model_name='associatepost',
            name='cta_label',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='associatepost',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='associatepost',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='associatepost',
            name='post_type',
            field=models.CharField(choices=[('UPDATE', 'Update'), ('OPPORTUNITY', 'Opportunity'), ('EVENT', 'Event'), ('RESOURCE', 'Resource')], max_length=20),
        ),
        migrations.AlterField(
            model_name='associatepost',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='associates.associate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_associates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'associate')},
            },
        ),
    ]
