# Generated by Django 5.0.14 on 2026-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0004_add_user_to_associate'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatepost',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of course tags from hashtags'),
        ),
    ]
