# Generated by Django 5.0.14 on 2026-05-28 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0005_add_tags_to_associate_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='associatepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='associate_posts/'),
        ),
    ]
