# Generated by Django 5.0.14 on 2026-07-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associates', '0006_associatepost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate',
            name='tier',
            field=models.CharField(choices=[('FREE', 'Free'), ('STANDARD', 'Standard'), ('PREMIUM', 'Premium')], default='FREE', max_length=20),
        ),
    ]
