# Generated by Django 5.0.14 on 2025-10-02 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Society',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=20)),
                ('full_name', models.TextField()),
                ('logo', models.CharField(default='🏛️', max_length=10)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hubs', models.ManyToManyField(blank=True, related_name='societies', to='hubs.careerhub')),
            ],
            options={
                'verbose_name_plural': 'Societies',
                'db_table': 'societies',
                'ordering': ['name'],
            },
        ),
    ]
