# Generated by Django 5.0.14 on 2025-10-06 14:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('societies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocietyPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('announcement', 'Announcement'), ('question', 'Question'), ('opportunity', 'Opportunity'), ('discussion', 'Discussion')], default='discussion', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('upvotes', models.IntegerField(default=0)),
                ('downvotes', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='society_posts', to=settings.AUTH_USER_MODEL)),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='societies.society')),
            ],
            options={
                'db_table': 'society_posts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['society', '-created_at'], name='society_pos_society_4b6dd7_idx'), models.Index(fields=['post_type'], name='society_pos_post_ty_3ddb78_idx')],
            },
        ),
    ]
