# Generated by Django 5.0.14 on 2026-05-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_achievement_userachievement_useractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('novice', 'Novice'), ('contributor', 'Contributor'), ('expert', 'Expert'), ('admin', 'Admin')], default='novice', max_length=20),
        ),
    ]
