# Generated by Django 5.0.14 on 2026-07-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_trials_balance',
            field=models.IntegerField(default=1, help_text='Number of AI advisor trials remaining'),
        ),
    ]
