# Generated by Django 5.0.14 on 2025-10-07 06:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hubs', '0002_alter_vote_votable_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='careerhub',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='hub_banners/'),
        ),
        migrations.AddField(
            model_name='careerhub',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careerhub',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='joined_hubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='careerhub',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='careerhub',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='post',
            name='is_expert_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
