# Generated by Django 5.0.14 on 2025-10-02 04:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('logo', models.CharField(default='🎓', max_length=10)),
                ('established', models.IntegerField()),
                ('ranking', models.IntegerField()),
                ('students', models.CharField(max_length=20)),
                ('website', models.URLField()),
                ('description', models.TextField()),
                ('facilities', models.JSONField(default=list)),
                ('accreditation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'db_table': 'universities',
                'ordering': ['ranking'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('Technology', 'Technology'), ('Medicine', 'Medicine'), ('Engineering', 'Engineering'), ('Law', 'Law'), ('Business', 'Business'), ('Education', 'Education'), ('Healthcare', 'Healthcare')], max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('cluster_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('modules', models.JSONField(default=list)),
                ('career_paths', models.JSONField(default=list)),
                ('mandatory_subjects', models.JSONField(default=list)),
                ('alternative_subjects', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'courses',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['category'], name='courses_categor_33f89e_idx'), models.Index(fields=['cluster_points'], name='courses_cluster_efec88_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseUniversity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fees_ksh', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cutoff_points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('course_url', models.URLField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='courses.course')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.university')),
            ],
            options={
                'db_table': 'course_universities',
                'unique_together': {('course', 'university')},
            },
        ),
    ]
