# Generated by Django 5.0.14 on 2025-10-12 18:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('hubs', '0007_careerhub_related_societies'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseuniversity',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='ProgramTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag_type', models.CharField(choices=[('primary', 'Primary Tag'), ('secondary', 'Secondary Tag'), ('related', 'Related Tag')], default='related', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='Algorithm confidence score (0.0-1.0)')),
                ('keywords_matched', models.JSONField(default=list, help_text='Keywords that matched for this tag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_tags', to='courses.course')),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_programs', to='hubs.careerhub')),
            ],
            options={
                'db_table': 'program_tags',
                'indexes': [models.Index(fields=['course', 'tag_type'], name='program_tag_course__ce6198_idx'), models.Index(fields=['hub', 'tag_type'], name='program_tag_hub_id_c80d62_idx'), models.Index(fields=['confidence_score'], name='program_tag_confide_7a2a31_idx')],
                'unique_together': {('course', 'hub')},
            },
        ),
    ]
