# Generated by Django 5.0.14 on 2025-10-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cluster_formula',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='course',
            name='cluster_subjects',
            field=models.JSONField(default=list),
        ),
    ]
