# Generated by Django 5.0.14 on 2026-03-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_courseuniversity_unique_together_programtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='careers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='cons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='pros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='courseuniversity',
            name='cutoff_2023',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='2023 cutoff points', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='courseuniversity',
            name='cutoffs',
            field=models.JSONField(blank=True, default=dict, help_text='Cutoff points per year'),
        ),
        migrations.AddField(
            model_name='courseuniversity',
            name='programme_name',
            field=models.CharField(blank=True, help_text='Specific programme name e.g., BACHELOR OF ARTS (WITH IT)', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='courseuniversity',
            name='requirements',
            field=models.JSONField(blank=True, default=dict, help_text='Subject requirements'),
        ),
        migrations.AlterField(
            model_name='course',
            name='alternative_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='career_paths',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='cluster_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='mandatory_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterUniqueTogether(
            name='courseuniversity',
            unique_together={('course', 'university')},
        ),
        migrations.DeleteModel(
            name='ProgramTag',
        ),
    ]
