# Generated by Django 5.0.14 on 2026-03-19 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_careers_course_cons_course_pros_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['category', 'cutoff_2023']},
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_cluster_efec88_idx',
        ),
        migrations.AlterUniqueTogether(
            name='courseuniversity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='avg_fees_ksh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cutoff_2022',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='cutoff_2023',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='institution',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_enriched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='programme_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='related_hub',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_requirement_1',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_requirement_2',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_requirement_3',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_requirement_4',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='alternative_subjects',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='career_paths',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='careers',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='course',
            name='cluster_formula',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cluster_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cluster_subjects',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='cons',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='mandatory_subjects',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='modules',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='pros',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='all_subjects',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='cluster_subjects',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='universities', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='cutoff_2022',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='cutoff_2023',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='cutoff_points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='cutoffs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='fees_ksh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='programme_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='courseuniversity',
            name='requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['related_hub'], name='courses_related_861daf_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['institution'], name='courses_institu_f2206f_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['cutoff_2023'], name='courses_cutoff__d9b4ec_idx'),
        ),
    ]
