# Generated by Django 5.0.14 on 2026-05-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='accreditation',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='university',
            name='established',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='university',
            name='logo',
            field=models.CharField(blank=True, default='🎓', max_length=10),
        ),
        migrations.AlterField(
            model_name='university',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='university',
            name='students',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
