# Generated by Django 5.0.14 on 2026-05-27 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AICareerProsCons',
            new_name='CareerProsCons',
        ),
    ]
