# Generated by Django 5.0.14 on 2025-10-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicprofile',
            name='kcse_mean_points',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='academicprofile',
            name='kcse_school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
