# Generated by Django 5.0.14 on 2025-10-09 06:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_academicprofile_kcse_mean_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('first_post', 'First Post'), ('helpful_contributor', 'Helpful Contributor'), ('active_member', 'Active Member'), ('knowledge_seeker', 'Knowledge Seeker'), ('community_builder', 'Community Builder'), ('goal_setter', 'Goal Setter'), ('profile_complete', 'Profile Complete'), ('streak_7', '7-Day Streak'), ('top_contributor', 'Top Contributor')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='🏆', max_length=20)),
                ('color', models.CharField(default='bg-yellow-100', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'achievements',
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('is_displayed', models.BooleanField(default=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_achievements',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('post_created', 'Post Created'), ('comment_made', 'Comment Made'), ('post_upvoted', 'Post Upvoted'), ('comment_upvoted', 'Comment Upvoted'), ('hub_joined', 'Hub Joined'), ('bookmark_added', 'Bookmark Added'), ('profile_updated', 'Profile Updated'), ('achievement_earned', 'Achievement Earned')], max_length=30)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='user_activi_user_id_c742e0_idx'), models.Index(fields=['activity_type', 'created_at'], name='user_activi_activit_1c12f9_idx')],
            },
        ),
    ]
